# Generated by Django 3.2 on 2021-04-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('dt', models.DateTimeField(db_index=True, verbose_name='Дата/время')),
                ('team', models.BigIntegerField(verbose_name='Команда')),
                ('category', models.CharField(choices=[('м', 'Молоко'), ('в', 'Вода'), ('п', 'Пища')], default='п', max_length=3, verbose_name='Категория')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Название еды')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'Прием еды',
                'verbose_name_plural': 'Приемы еды',
            },
        ),
        migrations.CreateModel(
            name='GymnasticsRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('dt', models.DateTimeField(db_index=True, verbose_name='Дата/время')),
                ('team', models.BigIntegerField(verbose_name='Команда')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность, мин')),
            ],
            options={
                'verbose_name': 'Гимнастика',
                'verbose_name_plural': 'Гимнастика',
            },
        ),
        migrations.CreateModel(
            name='OtherEventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('dt', models.DateTimeField(db_index=True, verbose_name='Дата/время')),
                ('team', models.BigIntegerField(verbose_name='Команда')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Другое событие',
                'verbose_name_plural': 'Другие события',
            },
        ),
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('dt', models.DateTimeField(db_index=True, verbose_name='Дата/время')),
                ('team', models.BigIntegerField(verbose_name='Команда')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность, мин')),
            ],
            options={
                'verbose_name': 'Сон',
                'verbose_name_plural': 'Сон',
            },
        ),
        migrations.CreateModel(
            name='SummaryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('dt', models.DateTimeField(db_index=True, verbose_name='Дата/время')),
                ('team', models.BigIntegerField(verbose_name='Команда')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('event_id', models.BigIntegerField(verbose_name='ID события')),
                ('event_type', models.CharField(choices=[('еда', 'Питание'), ('прг', 'Прогулка'), ('гим', 'Гимнастика'), ('др', 'Другое событие'), ('сон', 'Сон'), ('тлт', 'Туалет')], max_length=3, verbose_name='Тип события')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Записи журнала',
            },
        ),
        migrations.CreateModel(
            name='ToiletRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('dt', models.DateTimeField(db_index=True, verbose_name='Дата/время')),
                ('team', models.BigIntegerField(verbose_name='Команда')),
                ('category', models.PositiveSmallIntegerField(choices=[(1, 'Мало'), (2, 'Как обычно'), (3, 'Много'), (4, 'Реально шок')], verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Туалет',
                'verbose_name_plural': 'Туалет',
            },
        ),
        migrations.CreateModel(
            name='WalkRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('dt', models.DateTimeField(db_index=True, verbose_name='Дата/время')),
                ('team', models.BigIntegerField(verbose_name='Команда')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность, мин')),
            ],
            options={
                'verbose_name': 'Прогулка',
                'verbose_name_plural': 'Прогулки',
            },
        ),
    ]
