# Generated by Django 3.2 on 2021-05-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodrecord',
            options={'ordering': ['dt'], 'verbose_name': 'Прием еды', 'verbose_name_plural': 'Приемы еды'},
        ),
        migrations.AlterModelOptions(
            name='gymnasticsrecord',
            options={'ordering': ['dt'], 'verbose_name': 'Гимнастика', 'verbose_name_plural': 'Гимнастика'},
        ),
        migrations.AlterModelOptions(
            name='othereventrecord',
            options={'ordering': ['dt'], 'verbose_name': 'Другое событие', 'verbose_name_plural': 'Другие события'},
        ),
        migrations.AlterModelOptions(
            name='sleeprecord',
            options={'ordering': ['dt'], 'verbose_name': 'Сон', 'verbose_name_plural': 'Сон'},
        ),
        migrations.AlterModelOptions(
            name='summaryrecord',
            options={'ordering': ['dt'], 'verbose_name': 'Запись журнала', 'verbose_name_plural': 'Записи журнала'},
        ),
        migrations.AlterModelOptions(
            name='toiletrecord',
            options={'ordering': ['dt'], 'verbose_name': 'Туалет', 'verbose_name_plural': 'Туалет'},
        ),
        migrations.AlterModelOptions(
            name='walkrecord',
            options={'ordering': ['dt'], 'verbose_name': 'Прогулка', 'verbose_name_plural': 'Прогулки'},
        ),
    ]
